apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.db.name }}
spec:
  selector:
    app: {{ .Values.db.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.db.port }}
      targetPort: {{ .Values.db.port }}
  clusterIP: None